name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install & build
        run: yarn install --frozen-lockfile && yarn build

      - uses: shallwefootball/s3-upload-action@master
        name: Update prerelease
        with:
          aws_key_id: ${{ secrets.DEGENX_DOCS_PRERELEASE_AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEGENX_DOCS_PRERELEASE_AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.DEGENX_DOCS_PRERELEASE_AWS_BUCKET }}
          source_dir: "build"
          destination_dir: ""
